### ISSUE TITLE
Failed to build AkamaiOPEN-edgegrid-C-Sharp Open API on OSX

### ISSUE THREAD

**Issue by akamaiICA** [akamai/AkamaiOPEN-edgegrid-C-Sharp#3]
Hello,
I installed Visual Studio on my Mac and I tried to build the "AkamaiOPEN-edgegrid-C-Sharp" packagge (GitHub - akamai-open/AkamaiOPEN-edgegrid-C-Sharp ) but it failed to build with the below errors. I'm hoping someone know the solution for it. I google for solutions but couldn't find anything useful. I do see the package "System.Net.Http" is included in the build file but I don't know why it's still complaining. Thanks much!

From build file:
### <ItemGroup>

```
<Reference Include="Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" />
<Reference Include="System" />
<Reference Include="System.Net" />
<Reference Include="System.Net.Http" />
```

  </ItemGroup>

Error outputs:

XBuild Engine Version 14.0
Mono, Version 4.4.2.0
Copyright (C) 2005-2013 Various Mono authors
Build started 8/5/2016 3:35:52 PM.

---

Project "/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/Akamai.EdgeGrid.Auth.sln" (default target(s)):
  Target ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
  Target Build:
  Project "/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/EdgeGridAuth.csproj" (default target(s)):
  Target PrepareForBuild:
  Configuration: Debug Platform: AnyCPU
  Target ResolveAssemblyReferences:
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' not resolved
  For searchpath {CandidateAssemblyFiles}
  Warning: {CandidateAssemblyFiles} not supported currently
  For searchpath {HintPathFromItem}
  HintPath attribute not found
  For searchpath {TargetFrameworkDirectory}
  Considered target framework dir /Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api, assembly named 'System.Net.Http' not found.
  For searchpath {PkgConfig}
  Considered System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, but could not find in any pkg-config files.
  For searchpath {GAC}
  Considered 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL', but an assembly with the specific version not found.
  For searchpath {RawFileName}
  Considered 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' as a file, but the file does not exist
  For searchpath bin/Debug/
  Considered '/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/bin/Debug/System.Net.Http' as a file, but the file does not exist
  Considered '/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/bin/Debug/System.Net.Http.exe' as a file, but the file does not exist
  Considered '/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/bin/Debug/System.Net.Http.dll' as a file, but the file does not exist
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'System.Net.Http.WebRequest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' not resolved
  For searchpath {CandidateAssemblyFiles}
  Warning: {CandidateAssemblyFiles} not supported currently
  For searchpath {HintPathFromItem}
  HintPath attribute not found
  For searchpath {TargetFrameworkDirectory}
  Considered target framework dir /Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api, assembly named 'System.Net.Http.WebRequest' not found.
  For searchpath {PkgConfig}
  Considered System.Net.Http.WebRequest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, but could not find in any pkg-config files.
  For searchpath {GAC}
  Considered 'System.Net.Http.WebRequest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL', but an assembly with the specific version not found.
  For searchpath {RawFileName}
  Considered 'System.Net.Http.WebRequest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' as a file, but the file does not exist
  For searchpath bin/Debug/
  Considered '/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/bin/Debug/System.Net.Http.WebRequest' as a file, but the file does not exist
  Considered '/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/bin/Debug/System.Net.Http.WebRequest.exe' as a file, but the file does not exist
  Considered '/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/bin/Debug/System.Net.Http.WebRequest.dll' as a file, but the file does not exist
  Target GenerateSatelliteAssemblies:
  No input files were specified for target GenerateSatelliteAssemblies, skipping.
  Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
  Target CoreCompile:
  Tool /Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/Akamai.EdgeGrid.Auth.dll ClientCredential.cs EdgeGridV1Signer.cs Utils.cs IRequestSigner.cs Properties/AssemblyInfo.cs /target:library /define:"DEBUG;TRACE" /nostdlib /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/System.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/System.Net.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/System.Xml.Linq.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/System.Data.DataSetExtensions.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/Microsoft.CSharp.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/System.Data.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/System.Xml.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/System.Core.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.0-api/mscorlib.dll /warn:4
EdgeGridV1Signer.cs(24,18): error CS0234: The type or namespace name `Http' does not exist in the namespace`System.Net'. Are you missing `System.Net.Http' assembly reference?
  Task "Csc" execution -- FAILED
  Done building target "CoreCompile" in project "/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/EdgeGridAuth.csproj".-- FAILED
  Done building project "/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/EdgeGridAuth.csproj".-- FAILED
  Task "MSBuild" execution -- FAILED
  Done building target "Build" in project "/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/Akamai.EdgeGrid.Auth.sln".-- FAILED
Done building project "/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/Akamai.EdgeGrid.Auth.sln".-- FAILED
Build FAILED.
Warnings:
/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/Akamai.EdgeGrid.Auth.sln (default targets) ->
(Build target) ->
/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/EdgeGridAuth.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->
  /Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' not resolved
  /Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'System.Net.Http.WebRequest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' not resolved
Errors:
/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/Akamai.EdgeGrid.Auth.sln (default targets) ->
(Build target) ->
/Users/avu/Work/GIT/AkamaiOPEN-edgegrid-C-Sharp/EdgeGridAuth/EdgeGridAuth.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
  EdgeGridV1Signer.cs(24,18): error CS0234: The type or namespace name`Http' does not exist in the namespace `System.Net'. Are you missing`System.Net.Http' assembly reference?
  2 Warning(s)
  1 Error(s)
Time Elapsed 00:00:00.7505610

**Comment by AstinCHOI** [comment]
Hi @akamaiICA, 

you can install the package for System.Net.Http and remove the error as below.

In the Menu Bar,
**Project > Add NuGet Packages.. > then input "Microsoft HTTP Client Libraries" > Add Package.**

The error will disappear !

_My test env: Mac 10.12.2, Visual Studio Preview 3, mono 4.8.0_

Thanks.
